name: Rust Build and Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build_and_release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact_path: target/release/ctags_ls.exe
            zip_name: ctags_ls-windows-x86_64.zip
          - os: ubuntu-latest
            artifact_path: target/release/ctags_ls
            zip_name: ctags_ls-linux-x86_64.zip
          - os: macos-latest
            artifact_path: target/release/ctags_ls
            zip_name: ctags_ls-macos-x86_64.zip

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build the project
        run: cargo build --release

      - name: Zip artifact (Windows)
        if: matrix.os == 'windows-latest'
        run: Compress-Archive -Path ${{ matrix.artifact_path }} -DestinationPath ${{ matrix.zip_name }}
        shell: pwsh

      - name: Zip artifact (Unix)
        if: matrix.os != 'windows-latest'
        run: zip ${{ matrix.zip_name }} ${{ matrix.artifact_path }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            This is a release for ctags_ls version ${{ github.ref_name }}.
            Please refer to the changelog for details.
          files: |
            ${{ matrix.zip_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
