name: Rust Build and Release

on:
  push:
    tags:
      - 'v*'  # Trigger the workflow when a tag starting with 'v' is pushed, indicating a version change

jobs:
  build_and_release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build the project
        run: cargo build --release

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            This is a release for ctags_ls version ${{ github.ref_name }}.
            Please refer to the changelog for details.
          files: |
            target/release/ctags_ls${{ '.exe' if matrix.os == 'windows-latest' else '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
